* This marker serves as a sandbox for my own thoughts about happiness in relation to causality as I currently understand it.
* I can only effectively make plans insofar as this life, so this assessment is bounded between the present and my death.
* With a natural death, I may live between 70-120 years.
** I have heard that some people managed to live this long, hence the high upper bound.
* Realistically, I can expect to live up to 80.
* Death can occur at any moment, so at least two kinds of activities should be established:
** Conservative, expedient activities to ensure favorable outcomes even in the face of sudden death.
** Liberal, long term activities building upon the conservative for greater certainty and outcomes.
* The Buddha's teaching and soteriological goal of nibbana seems to me to be the most likely of all alternatives, said to be directly knowable in this very life. For this reason among many others, there is no excuse not to walk this path to the best of my ability so that I may see the goal for myself.
** At the very least, maintain strong faith that all (things?) are impermanent, as one sutta states that one with sufficient faith in this is incapable of dying without gaining the fruit of stream entry.
* The Buddhist view presupposes factors to conscious experience outside that of its biological factors, i.e. karma. This however is at odds with the prevailing materialist view of consciousness emergent of material activity.
** It is of my opinion that the materialist viewpoint is utterly irrational and irreconcilable with the fundamental nature of experience.
** Writing all this was pointless..
* Kamma
:PROPERTIES:
:heading: 2
:END:
** If one fails to enter the stream, they must rely on their kamma to reappear in a fortunate realm.
** The Sangha is the supreme field of merit.
** Kinship is a poor thing compared to the happiness of the gods.
** Therefore, one not fully intent on nibbana ought to dedicate their life to maximizing merit via ethics, generosity, and meditation, and well settle their mind onto their chosen destination of rebirth.
** Where to be reborn?
** Find a realm that is suitable for further generation of merit, yet sufficiently pleasant.
** Any of the sensual heavens will do, but which is the most efficient option?
** Are the higher heavens more "karmically" expensive?
** But for one intent on nibbana, their practice and determination for the goal is sufficient, even if at the expense of optimizing a heavenly existence.
*** It is said that a mind that inclines towards nibbana will surely reach its goal.
*** A truly virtuous practitioner is bound to be lifted up in to the heavens even without a determination.
* Since there is still uncertainty regarding the Buddhist path, it is proper for you to clear your doubts through research.
* It is also proper to generate as much wealth as is reasonable to pour back into research and merit.
* AI tells me that most billionaires makes 80% of their wealth around 20 years into their careers.
* So maximize wealth for your final rounds of research and implementation, as well as merit generation, and then dedicate the rest of your years to the renunciate life, shooting straight for nibbana.
** Hopefully by then you will already be a stream enterer, as is very much possible as a serious layman.
* Your business endeavors should be as helpful to the goals of this organisation as much as possible.
* Sensory enjoyment is useless
** The contemplative lifestyle with mastery of jhana is far superior
* Therefore sensory delights are only useful as [[Authors/Shashank Rajesh/Skillful Thirst]].
* Ventures
:PROPERTIES:
:heading: 2
:END:
* Possible business ventures in line with the goal:
* AI
* BCI
* Computing
* Instrumentation (for empirical measurement)
* Alien communication
* Dream manipulation
* Brain manipulation
* Entheogenic alien communication