* Offense
#+BEGIN_QUOTE
2. annoyance or resentment brought about by a perceived insult to or disregard for oneself or one's standards or principles: I didn't intend to give offense | /he went out, making it clear he'd taken offense./ (macOS Dictionary)
#+END_QUOTE
* As an Indian American, offense is something I understand quite well.
* There are two kinds:
** Bearing abuse to something true which one is associated with.
*** The negative aspects of modern India and culture, as is the case with any culture.
** Bearing abuse to something untrue which one is perceived to be associated with.
*** The maliciously exaggerated and sometimes fabricated negative perceptions and prejudices of India and Indians, often quite hypocritical.
* In either case, one cognizes mental displeasure highly conducive to [[Terms/Involvement]] and [[Terms/Stress]] as a result of the deep conditioning of personal identity.
* Solutions
:PROPERTIES:
:heading: 2
:END:
* The non-dual solution to this issue involves the transcendence of identification leading to immunity to displeasure, but to what extent can it be avoided within duality?
* Rectification
** External
*** Modify the objectionable external factors from which offense can originate.
*** Correct prejudices and false perceptions through education. This is quite difficult, and can be avoided in time by solving the root issues instead.
*** Correct the factors that lead others to abuse.
** Internal
*** [[Cognitive Reframing][Cease to identify]] with the objectionable phenomena.
**** Mentally
**** Physically (this is not currently feasible)