* A human being is a psychophysical complex of biology and mind.
* The body is itself is [[Markers/Human Death][bound to die]].
* While it persists and one is awake, [[Terms/Consciousness]] tends to take basis on physical [[Terms/Sensation]].
* Though possible to temporarily alter or suspend this process through natural or artificial means, it will inevitably return to normality so long as the body is functioning properly.
* Sources of displeasure:
** Bodily sensation
*** Humans are capable and indeed often of experience many kinds of displeasure and pain by way of the body. It is perhaps the biggest drawback to human existence.
** Sights
*** However beautiful a person may look, they cannot escape the fact that the human body is ultimately a disgusting bag of bones and flesh, constantly oozing out all kinds of unpleasant matter. It must be routinely maintained in order to maintain its relative beauty.
*** But most people aren't exactly handsom or pretty, and so they would feel displeasure through sights of their own body, as well as that of others.
** Smells
*** There are many unpleasant smells out in the world.
*** The human body itself is naturally repulsive when unmaintained.
** Sounds
*** In most places,