#+author: [[Authors/Shashank Rajesh]]
#+controls: [[Terms/Feeling]], [[Terms/Involvement]]

* [[Terms/Happiness]] through [[Terms/Involvement]] to [[Terms/Pleasure]] felt through the five physical senses and the thoughts and perceptions derivative of them.
* Consists of six [[Dhamma/18 Mental Preoccupations][mental preoccupations]] with pleasure.
* Typically volatile, requiring constant novelty through change in sensation to maintain pleasure.
** The  "hedonic treadmill".
* Enjoyment requires a constant relishing of feeling with the consequence of the flaring up of the stress of thirst if there is a lack of compliance to the desire.
* Monotony can shift one's [[Terms/Perception]] so that those sensations become unpleasant.
* It can be modeled as a vortex:
** Its unpleasant to resist the pull before entering, pleasant to enter, pleasant to relish, unpleasant to resist the pull on the inside, unpleasant to escape, and pleasant after its escaped.
* This form of enjoyment does not typically involve much effort, often taking the form of procrastination.
* Can be used as an [[Dhamma/Escaping Pain with Pleasure][escape from displeasure]].
* When feeling displeasure outside the vortex, be it from external stimuli or internal thought, one is oppressed from the outside. When enjoying sensual pleasures, constantly escaping the displeasure of unresolved desire, one is oppressed from the inside.